In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [10]:
df=pd.read_csv(r'R:\aiml\ml\regression\student_pass_dataset.csv')

In [11]:
df.head(3)

   Hours_Studied  Attendance  Pass
0              6          68     1
1              3          51     1
2             10          93     1

In [12]:
x=df.drop('Pass',axis=1)
x.head(3)

   Hours_Studied  Attendance
0              6          68
1              3          51
2             10          93

In [13]:
y=df['Pass']

In [14]:
x_train , x_test ,y_train , y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
model=LogisticRegression()
model.fit(x_train,y_train)
prediction=model.predict(x_test)

In [17]:
print(prediction)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]

In [26]:
prediction2=model.predict([[6,53]])

c:\Users\layap\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [27]:
print(prediction2)

[1]